---
title: "p8105_hw4_zw2975"
author: "Zhiyu Wei"
date: 2024-10-28
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(plotly)
library(p8105.datasets)
library(flexdashboard)
library(lubridate)
```

## Problem 2


Column {data-width=2000}
-----------------------------------------------------------------------

### Cuisine type comaprison

```{r cuisine type camparison}
rest_inspec |> 
  count(cuisine_description) |> 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) |> 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis")
```
```{r clean data, include = FALSE}
data("rest_inspec")

# Clean dataset:
# 1. exclude na
# 2. mutate variable type
# 3. exclude unnecessary variables
rest_inspec = janitor::clean_names(rest_inspec)
rest_inspec = rest_inspec |>
  drop_na()|>
  mutate(inspec_date = as.Date(inspection_date)) |>
  mutate(grad_date = as.Date(grade_date)) |>
  select(-grade_date, -inspection_date) |>
  filter(!boro == "missing")
```


Column {data-width=1800}
-----------------------------------------------------------------------

### Comparison of scores in each borough

```{r plot 1}
rest_inspec |> 
  filter(!boro == "Missing") |>
  plot_ly(x = ~boro, y = ~score, color = ~boro, type = "box", colors = "viridis")
```

### Annual trend of Manhattan restuarant inspection 

```{r annual trend plot}
rest_inspec |>
  filter(!grade == "Not Yet Graded", boro == "MANHATTAN")|>
  ggplot(aes(x = inspec_date, y = score, color = grade)) +
  geom_point(alpha = 0.1)+
  labs(title = "Annual Trend of NYC Restaurant Inspection Grades", x = "Year", y = "Score") 
```


